name: Lint and build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn lint
      - run: yarn style:check
      - run: yarn build
